### ISSUE TITLE
Cache directory should be configurable

### ISSUE THREAD

**Issue by kelson42** [offspot/image-creator#11]
Currently, it is not, the cache directory is in the (image) output directory. This brings problems:
* This is not configurable and it exists various scenarios where this is not wanted
* It is "hidden", ie. if the user does not look accurately to the fs, it can miss the fact that there is a cache (just had a user report about that).
* The way the installer behaves is implicit

IMO the current behaviour is an appropriate default behaviour. But it should be visible/configuratble in the UI/cmd. I would propose to put it below the output directory file picker. Once the output directory has been set, configure the cache directory automatically (if not already configured manually). 

This ticket is a follow of offspot/kiwix-hotspot#623.

**Comment by rgaudin** [comment]
Closing this as useless given we have no cache feature yet and there's already #1 that covers it.
