### ISSUE TITLE
Prevent download bomb

### ISSUE THREAD

**Issue by rgaudin** [offspot/image-creator#15]
The standard use case of image-creator is to be fed with arbitrary links to content that will be stored in the target image.
We don't care about what those files contain but given the frontend service will not validate neither, we should protect ourselves (or our running host to be more precise) against easy filesystem size attacks.

It would be easy for an attacker to serve a file on a lying server sending a reasonable `Content-Length` but sending enormous amounts of data when fetching.

Our downloader should stop/halt once the expected size has been reached.

**Comment by kelson42** [comment]
@rgaudin Does the new downloader infrastructure check this?

**Comment by rgaudin** [comment]
I'll have to test. Now that we use aria we don't have control over this but I think aria itself might be unhappy and fail the download.

**Comment by rgaudin** [comment]
OK, aria2 (as all major http client I tested actually) already handles this ans consider download complete once it has reached the provided Content-Length.
