### ISSUE TITLE
Proper naming?

### ISSUE THREAD

**Issue by kelson42** [offspot/image-creator#22]
If I read https://github.com/kiwix/overview/wiki/Branding, this software should be called « Imager », not « Image-creator »?!

**Comment by rgaudin** [comment]
No, this software is an underlying tool that would be used by Imager, the new name of Kiwix Hotspot.
image creator has no knowledge of Kiwix, ZIM, or its catalog : it builds an image from a list of files.
It cannot replace Kiwix Hotspot

**Comment by kelson42** [comment]
@rgaudin Still unclear to me, not sure why. What is the difference in term of input/output with the imager?

**Comment by rgaudin** [comment]
This has been discussed long and large (not debated, we all agreed). Have you forgotten or do you want to question it? Here's the new stack:

| Tool | Desc |
| --- | --- |
| `base-image` | raspiOS-like _base_ image builder: adds/removes package, adds some configuration, tweaks and tools, installs `offspot_runtime` (part of `offspot_config`)
| `offspot_runtime` | set of scripts to (re-)configure some stuff on boot: network, WiFi, etc. |
| `offspot_config` | library for parsing/creating offspot YAML config. Include a Config Builder and an App Catalog |
| `image-creator` | _somewhat_-generic Image creator taking a YAML config as input. YAML config lists all files to download, and includes a complete docker-compose. This is not user-friendly at all. Linux only, runs as root. |
| Imager Service (Cardshop) | Web UI to select content. Uses the offspot-config builder to produce YAML. Calls image-creator in worker to build image then uploads it. |
| Imager App | **Not implemented yet**. kiwix-hotspot replacement. UI to select content and configure. Will use offspot-config builder to gen a YAML and call image-creator |

**Comment by kelson42** [comment]
@rgaudin I have forgotten and I question it. Now that things start to be OK, I also think more about this kibd of stuff.

The nice overview you just have wrotten deserve to be put in the documentstion (wiki?).

I still have a concern about the very similar names "imager" and "image-creator". Let me thonk more about that....

**Comment by kelson42** [comment]
I don't have something better in mind that what is currently ongoing in term on naming. If documentation is update, fine to me to close this issue.

**Comment by rgaudin** [comment]
I'll put it in offspot/overview and close

**Comment by rgaudin** [comment]
https://github.com/offspot/overview/tree/main
