### ISSUE TITLE
(How to) Download container images

### ISSUE THREAD

**Issue by kelson42** [offspot/image-creator#3]
It seems we agreed that we want to download container images in a form of (compressed?) tarballs.

These tarballs to be then at first RPI start (first usage?):
* Load in the local container image repository
* Run the image to create a container

This approach follows the `docker save` and `docker load` workflow.

But a few clarifications are still needed IMO to answer the following questions:
* How to download a tarball if the container runtime engine (`docker`) does not run in `image-creator`? Do we/Should we have a script which can deal with the the online image repository?
* How should we secure that the cache works (see #1) and is in sync with upstream online image repositories?
* Considering that compressing this container image tarballs would be beneficial (less data to download, less data to write to the SD image/card), it seems we might need to precompute these tarballs and store them somewhere... but how & where precisely?

**Comment by rgaudin** [comment]
> Do we/Should we have a script which can deal with the the online image repository?

That's the plan. There are a few versions of this available online, even in Python. There's work to be done to test it, adapt it, integrate it of course.

> How should we secure that the cache works (see https://github.com/offspot/image-creator/issues/1) and is in sync with upstream online image repositories?

Images are collections of stages identified with hashes. We can imagine we we reuse the image's hash (latest stage) as filename or something: we won't keep every layers ; we're not recreating docker. Anyway I think it's a bit early to decide those details.

> Considering that compressing this container image tarballs would be beneficial (less data to download, less data to write to the SD image/card), it seems we might need to precompute these tarballs and store them somewhere... but how & where precisely?

I'm not convinced at the moment. Why would we want to pre-compute it? It's almost exclusively downloads from the registry and as discussed above, it will be cached. As for compressing, I don't think it's a good idea neither:
- takes time and resources in the image-creator
- takes time and resources on the Pi at first boot. Can be **very long**
- Not much useful: images should be the smallest possible in any case and will be piped to docker load. I can't see cases where we'd have images with lots of compressable data inside, so I don't expect interesting compression ratios.

I see your comment about WikiFundi which is not a good example.

**Comment by rgaudin** [comment]
We'll have to build some of those images first anyway so we'll have data. At this point I think it would be counter productive but we'll see in time

**Comment by rgaudin** [comment]
Closing this ticket which is not actionable anymore. ATM we're looking at using https://github.com/offspot/docker-export to retrieve registry-stored images. Compressing can be discussed separately
