### ISSUE TITLE
Implement Downloader

### ISSUE THREAD

**Issue by rgaudin** [offspot/image-creator#9]
Most of the `image-creator`'s work consists of downloading files:
- base-image
- container images
- content to be placed on the card

Need is basic for now: given a URL, write it to a specified location on disk, reporting progress.
It should also be somewhat resilient to network hiccups

**Comment by kelson42** [comment]
For the (HTTP) downloading, we need:
* Reporting solution (time estimation, status, error details, etc..)
* Parallelisation of the download

**Comment by kelson42** [comment]
@rgaudin Might we close this issue now that https://github.com/offspot/image-creator/pull/31 has been merged?

**Comment by rgaudin** [comment]
Indeed ; I forgot to link it
